### ISSUE TITLE
[Feature Request] Organize the converted files

### ISSUE THREAD

**Issue by aidenmitchell** [kolbyg/X264toX265#2]
Pull data from the *arr APIs and organize the converted files into `TV Shows` and `Movies` folders, and for TV shows, organize them into folders for each show. This makes re-importing into *arr much easier.

For example:
Convert `Show S01E01` and put it into `ConversionOutputDir/TV Shows/Show`
Convert `Movie (2021)` and put it into `ConversionOutputDir/Movies`

**Comment by kolbyg** [comment]
Implemented in Beta v0.14. The series/movie file naming convention will follow the source file, but it will be placed into series/movie folders based on the "cleantitle" pulled by the API. I may add a setting to customize this a bit more later, but using cleantitle should allow the importer to grab it, as well as maintain compatibility across win/linux.
